### ISSUE TITLE
Some types of elements in previews do not get dark-mode styles

### ISSUE THREAD

**Issue by MichaelAllenWarner** [wikimedia/wikipedia-preview#232]
While some elements in the preview get dark-mode styles (e.g., the variable used in `.wikipediapreview-body p { color: var(--wikipediapreview-primary-color) }` resolves to a color whose value depends on whether dark-mode is enabled), others do not, rendering them visually inaccessible.

For example, here is a screenshot showing an `<ol>` in dark-mode:

![Image](https://github.com/user-attachments/assets/3bd75c75-e6a1-4c8b-a98e-f13598f68ef8)

And here is a screenshot showing some inline math-images in dark-mode:

![Image](https://github.com/user-attachments/assets/c9495ae8-1233-430d-a5eb-e665f375cc21)

I wonder if there might be some "systematic" way of handling dark-mode with these previews. For instance, could the script simply fetch the needed CSS from Wikipedia itself? (Or could the API have an option for something like this?) Just a thought; I don't know if it's feasible.

In any case, I believe that the particular examples above could be solved with CSS rules like the following (though I don't know if they're really the "right" rules):

```css
.wikipediapreview-body ol {
  color: var(--wikipediapreview-primary-color);
}

.mwe-math-element {
  filter: var(--wikipediapreview-filter-setting);
}
```
